### ISSUE TITLE
[proposition] Set the format with file extension

### ISSUE THREAD

**Issue by Neolex-Security** [skorokithakis/pastebinit#1]
Hi ! 
This is not an issue but I have a suggestion, I hope i'm in the right place...
The format could be set automatically to "python" if the file specified by -i have a .py extension ?
```
-i prog.py => -f python
-i prog.c   => -f C 
etc..
```
If you don't have the time to do it I can try myself if you want !
Have a good day

**Comment by skorokithakis** [comment]
That's a good suggestion, unfortunately this repository is just a dump of another repo that was looking abandoned. If you want, there's another tool that's actively maintained by me, for www.pastery.net:

https://github.com/skorokithakis/bakeit/

**Comment by Neolex-Security** [comment]
Oh thank you! Your tool looks great, i'm gonna use it ! 
Have a good day !
